name: Main
on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/asdf-cached-install

      - name: Check
        run: ./go library:check

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: some-database
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: super-secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/asdf-cached-install

      - name: Test
        run: ./go library:test:all
        env:
          DB_HOST: postgres
          DB_PORT: 5432

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/asdf-cached-install

      - name: Build
        run: ./go library:build

  prerelease:
    runs-on: ubuntu-latest
    needs: [ check, test, build ]
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        uses: ./.github/actions/asdf-cached-install

      - name: Authenticate with PyPi
        run: ./go poetry:login_to_pypi[${{ secrets.PYPI_API_KEY }}]

      - name: Publish
        run: ./go library:publish:prerelease

      - name: Configure git Author
        run: ./go repository:set_ci_author

      - name: Commit Release
        run: ./go repository:commit_release

      - name: Push Release Commit
        run: ./go repository:push

  release:
    runs-on: ubuntu-latest
    needs: [ prerelease ]
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Install tools
        uses: ./.github/actions/asdf_install

      - name: Authenticate with PyPi
        run: ./go poetry:login_to_pypi[${{ secrets.PYPI_API_KEY }}]

      - name: Publish
        run: ./go library:publish:release

      - name: Configure git Author
        run: ./go repository:set_ci_author

      - name: Commit Release
        run: ./go repository:commit_release

      - name: Push Release Commit
        run: ./go repository:push
